version: '3.7'

services:
  msyql:
    image: 'mysql:latest'
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
  mailer:
    image: schickling/mailcatcher
    ports: [1025,1080]
